

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' Create a list of graphical parameters for cairo
#' 
#' @param antialias antialias setting. One of: 
#'   c('default', none', 'gray', 'subpixel', 'fast', 'good', 'best')
#' @param line_width Numeric value for width of line. Default: NULL (Use 2.0)
#' @param line_end String indicating how line ends should be drawn.
#'       Default: NULL (use 'butt'). Valid values: 'butt', 'round', 'square'
#'       \describe{
#'          \item{\code{butt}}{start/stop the line exactly at the given coordinates}
#'          \item{\code{round}}{use a round ending}
#'          \item{\code{square}}{use a squared ending}
#'       }
#' @param line_join String indicating how lines should be joined.
#'        Default: NULL (use 'miter'). Valid values: 'miter', 'round', 'bevel'
#'        \describe{
#'          \item{\code{miter}}{Use a sharp angled corner}
#'          \item{\code{round}}{Use a rounded join}
#'          \item{\code{bevel}}{use a cut-off join}
#'        }
#' @param line_dash a vector of positive numeric values given the length of alternate
#'        'on' and 'off' portions of the stroke.
#' @param line_mitre_limit Numeric value. If current \code{line_join} is 'miter', then this limit is used
#'         to determine whether the lines should be joined with a bevel instead of a miter.
#'         Default: NULL (use internal default of \code{line_join = 10})
#' @param operator String specifying compositing operator. Default: "over".  
#'        Valid values: clear, source,
#'        over, in, out, atop, dest, dest-over, dest-in, dest-out, dest-atop,
#'        xor, add, saturate, multiply, screen, overlay, darken, lighten,
#'        dodge, burn, hard-light, soft-light, difference, exclusion, 
#'        hsl-hue, hsl-sat, hsl-color, hsl-luminosity. 
#'        For more details on operators, see Cairo's documentation
#'        \url{https://cairographics.org/operators/}
#' @param fill_rule 'winding' or 'even-odd'. Default: winding
#' @return Named list of graphical parameters
#' @examples
#' cpar(line_width = 1)
#' @family parameter related functions
#' @export
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cpar <- function(
    antialias = NULL,
    line_width = NULL, line_end = NULL, line_join = NULL, line_mitre_limit = NULL, line_dash = NULL, 
    operator = NULL,
    fill_rule = NULL) {
  
  params <- list(
    antialias  = antialias,
    
    line_width = line_width,
    line_end   = line_end,
    line_join  = line_join,
    line_mitre_limit = line_mitre_limit,
    line_dash  = line_dash,
    
    operator = operator,
    fill_rule = fill_rule
  )
  
  # remove NULLs
  Filter(Negate(is.null), params)
}



#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' Set global drawing parameters.
#' 
#' These parameters exist globally, but can be overridden by passing a 
#' \code{params} argument to any drawing function
#' 
#' @inheritParams cr_rect
#' @param params Cairo parameters as generated by \code{\link{cpar}()}
#' @examplesIf interactive()
#' cr_params_set(cr, params = cpar())
#' @return Invisibly return the original \code{cairo raster} object
#' @family parameter related functions
#' @export
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cr_params_set <- function(cr, params) {
  invisible(
    .Call(cr_params_set_, cr, params)
  )
}



#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' Save and restore (push and pop) global parameter settings on a hidden internal stack
#' 
#' @inheritParams cr_rect
#' @examplesIf interactive()
#' cr_params_save(cr)
#' cr_params_restore(cr)
#' @return Invisibly return the original \code{cairo raster} object
#' @family parameter related functions
#' @export
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cr_params_save <- function(cr) {
  invisible(
    .Call(cr_params_save_, cr)
  )
}



#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#' @rdname cr_params_save
#' @export
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cr_params_restore <- function(cr) {
  invisible(
    .Call(cr_params_restore_, cr)
  )
}

